baseURL : https://qweekertom.github.io/blog
languageCode : en-us
title : bloggertom
publishDir : /docs/
theme : hugo-PaperMod
menu:
  main:
  - identifier: tags
    name: Topics
    title: tags
    url: /tags/
    weight: 10